version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  build:
    executor:
      name: node/default
      tag: '16.10'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Check if build is a pull request
          command: |
            if [ -n "$CIRCLE_PR_NUMBER" ]; then
              echo "This build is a pull request. Running specific jobs..."
              # Add your specific jobs here
              npm run build
            else
              echo "This build is not a pull request. Skipping specific jobs..."
            fi

workflows:
  run npm run build:
    jobs:
      - build:
          filters:
            branches:
              ignore: # List of branches to ignore
                - gh-pages